spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    spring:
      h2:
      console.enabled: true
      
  spring:
    jpa:
     properties:
      hibernate:
        show_sql: true
        format_sql: true
  logging:
   level:
    org:
      hibernate:
        type: trace    